CREATE TABLE trade_summary (
    ticker_code VARCHAR (5) NOT NULL,
    previous BIGINT,
    open_price BIGINT,
    first_trade BIGINT,
    high_price BIGINT,
    low_price BIGINT,
    closing_price BIGINT,
    change_price BIGINT,
    trading_volume BIGINT,
    trading_value BIGINT,
    frequency BIGINT,
    index_individual BIGINT,
    offer BIGINT,
    offer_volume BIGINT,
    bid BIGINT,
    bid_volume BIGINT,
    listed_share BIGINT,
    tradeable_share BIGINT,
    weight_for_index BIGINT,
    foreign_sell BIGINT,
    foreign_buy BIGINT,
    non_regular_volume BIGINT,
    non_regular_value BIGINT,
    non_regular_frequency BIGINT,
    trading_date DATE,
    created_at TIMESTAMP,
    UNIQUE(ticker_code, trading_date)
);
